Application view
braincee/blogging-app pull request #6
Opened 2022-10-25 14:29 UTC by braincee

In this branch `application-view`, these were the following requirements :

  - I implemented the design from the sneak peek wireframes.
  - I added basic styling views in `assests/stylesheets/application.css`

![185380799-dabcbbba-6231-4994-a3e4-50f4c7c61bf9](https://user-images.githubusercontent.com/78104544/197801062-96e926db-0bc3-4dff-94fe-175b04b8a50c.png)

![185380909-68f59468-9309-4e36-b1ef-b25ba56e9be6](https://user-images.githubusercontent.com/78104544/197801172-9a09ade8-bec8-46ec-8334-e77935851fa3.png)

![185380972-ce68f1e7-c8bc-4dc3-99cf-06839e29cfb5](https://user-images.githubusercontent.com/78104544/197801278-8d505959-e495-4c6c-bde2-3b186f743e94.png)

![185381032-302bd1fc-b79f-4b60-9d92-cbe437abfa03](https://user-images.githubusercontent.com/78104544/197801477-83193f0a-48d2-494a-867b-4d5e5c351949.png)

2022-10-25 15:13 UTC, BenMukebo requested changes
### Hi @braincee,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
- Descriptive README file.  ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-25 15:13 UTC, BenMukebo commented on app/views/posts/index.html.erb
> +  <%end %>
- [OPTIONAL ] Great job so far, But what do you think about using `Partials` which will allow you to extract pieces of code from your templates to separate files and also reuse them throughout your templates? 🤔 visit this link on [how to use Partials](https://riptutorial.com/ruby-on-rails/example/2875/partials) for more information 👍🏻 

Your view will look like: app/views/users/_user.html.erb, as a better practice instead of using @objects.each

```ruby
    # app/views/users/_user.html.erb

     #   HTML Code Here displaying
     #   user.photo, user.name and user.posts_counter

    # app/views/users/index.html.erb

    <%= render @users %>
```

2022-10-25 15:13 UTC, BenMukebo commented on app/views/users/index.html.erb
> +</div>
- [ ] Great job but I was unable to run your application from my local machine instead I get this error message about users 👇🏻 

![Screenshot from 2022-10-25 17-04-34](https://user-images.githubusercontent.com/79058364/197812201-60d75209-7d32-4809-80d3-d60e28d99613.png)


I am also trying to create a user from seed and console 👇🏻 but still getting the same error, please fix this:

![Screenshot from 2022-10-25 17-05-39](https://user-images.githubusercontent.com/79058364/197812425-aee2eca3-bce3-47e1-8472-cdb3db66961b.png)

2022-10-25 16:26 UTC, braincee commented on app/views/users/index.html.erb
> +</div>
**_I have attached screenshots displaying the views of the blog application on my machine working perfectly_** 

**************************************************


*******************************************

 -  **_This is a screenshot displaying all the `users`: http://127.0.0.1:3000/users_**


 
![Screenshot (21)](https://user-images.githubusercontent.com/78104544/197824348-bb4396cf-dab1-47a6-bb0f-28aea0912bbb.png)

*************************************






************************************

 **_- This is a screenshot of a specific `user` with id: http://127.0.0.1:3000/users/35_**


 
![Screenshot (16)](https://user-images.githubusercontent.com/78104544/197824790-7fe1d634-41e5-49dc-b568-4c288bbfae2d.png)


***********************************************






********************************

 **_- This is a screenshot of a specific `user` with a `user id` and `posts`: http://127.0.0.1:3000/users/35/posts_**


  
![Screenshot (17)](https://user-images.githubusercontent.com/78104544/197825669-cb4f635d-f017-43eb-a333-05be4c950d35.png)



*******************************************






*******************************************

 **_- This is a screenshot of a specific `user` with a `user id`, `posts` and specific` posts id`: http://127.0.0.1:3000/users/35/posts/29_**



![Screenshot (18)](https://user-images.githubusercontent.com/78104544/197826986-240dc4f6-afe4-4214-a85e-aa15cb9f9866.png)


**********************************************






************************************************

 **_- This is a screenshot of `user` data created in the rails console_**
 



![Screenshot (20)](https://user-images.githubusercontent.com/78104544/197826711-70219a8d-faaf-423e-a97c-fc57eaae1b44.png)

2022-10-25 16:43 UTC, m05e5 approved these changes
Hi @braincee , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)

## Highlights
✔️ your linters are all ok
✔️ Descriptive PR 

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-25 16:44 UTC, merged

2022-11-28 01:40 UTC, braincee commented
Thanks very much, @m05e5 and @BenMukebo 

Note: I have implemented all review and optional changes

![line-sticker-thank-you-sticker](https://user-images.githubusercontent.com/78104544/204173951-00a74d10-46f1-4efa-a132-62be9edae31e.gif)